version: '3.7'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./ssl/:/etc/nginx/ssl/
      - ./html/:/usr/share/nginx/html/
    ports:
      - 80:80 
      - 443:443
#    network_mode: host

